brazos=["triceps","biceps","planchas","barras","levantar pesas"]
piernas=["pantorrillas", "muslos", "sentadillas","polichinelas"]
torso=["planchas","abdominales","pectorales","salto de tijera", "face pull"]
cardio=["correr","trotar","nadar","saltar soga","burpee", "aerobicos"]
dieta_sobrepeso=["Desayuno: Leche deslactosada, jugo de naranja y 2 tostadas de pan integral con queso fresco","Almuerzo: 1 o 2 piezas de fruta con yogurt desnatado", "Cena: Verdura cocida al horno o a la plancha"]
dieta_obesidad=["Desayuno: Café o infusión, leche desnatada y pan con queso desnatado","Almuerzo: Ensalada de apio, nueces y uvas o pescado al horno con tomate","Cena: Ensalada de verduras"]
